### ISSUE TITLE
TVShow Time account keeps disconnecting

### ISSUE THREAD

**Issue by idtzoli** [popcorntime/popcorntime#113]
Operating System Version:

Windows 10 x64
Popcorn Time Version:

0.3.9
Download date:

17-03-2016
#### Expected Behaviour

I connected the TVShow Time API to sync my progress on watching tv shows.
#### Actual Behaviour

TVShow Time API keeps disconnecting at every exit and I have to reconnect at every launch.
#### Steps to repoduce the behaviour

1. Open Popcorn TIme
2. Authorize TVShow Time API
3. Close Popcorn Time
4. TVShow Time API is disconnected

**Comment by SeungRyul** [comment]
Also have the exact same problem. Hopefully it is fixed soon.

**Comment by VitorVRS** [comment]
I have already see this problem, tvshowtime authenticated token is not loaded from pct database in time to restore tvshowtime login.
I will try to solve this when i get free time.

**Comment by VitorVRS** [comment]
I still dont have time for this.
But i'll drop the "bug flow"
1. App init
2. Load ST api with no data
3. Load database api with ST token

This bug occurs because they load asynchornous(!?)

**Comment by VitorVRS** [comment]
@team-pct  this issue can be closed now.
