### ISSUE TITLE
Homebrew Error: Checksum for Cask 'popcorn-time-beta' does not match.

### ISSUE THREAD

**Issue by jacopodisi** [popcorntime/popcorntime#1145]
Operating System Version:
OS X 10.15.3

Popcorn Time Version:
popcorn-time-beta

Download date:
13 March 2020

#### Expected Behaviour
Install the latest [stable] beta version of popcorntime through homebrew with the following command:
`brew cask install https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time-beta.rb`

#### Actual Behaviour
Receive the following error after running the command:
```
Error: Checksum for Cask 'popcorn-time-beta' does not match.
Expected: 1afaf5e39e2c0a0602e853a50c0139b9f6ecd8682f0a7f59d0c78976c9ce0b19
  Actual: 99204ac1f79ba72eee0a6c336610f06fad9e5595cb2796e736fa7ebe87ab6831
```

#### Steps to reproduce the behaviour

1.  run `brew cask install https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time-beta.rb`

**Comment by ghost** [comment]
I got the same error just now with

- Easily install Popcorn Time via Homebrew (Cask) with `brew cask install https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb`

>     Error: Checksum for Cask 'popcorn-time' does not match.
>     Expected: 62002814ddac7587e447d0f8e7db5d7359ccca77893b79223f7b1f5c7d8992bf
>       Actual: c033562ea9a729f53798834bc721d0d5911bafe8c5a809138213f078c328ccd4

**Comment by team-pct** [comment]
Because the actual is c033562ea9a729f53798834bc721d0d5911bafe8c5a809138213f078c328ccd4

**Comment by ghost** [comment]
> Because the actual is c033562ea9a729f53798834bc721d0d5911bafe8c5a809138213f078c328ccd4

Why does `brew cask install ...` download a file with the wrong checksum

**Comment by team-pct** [comment]
It was fixed on last commit

**Comment by theonlygusti** [comment]
> It was fixed on last commit

I still get the error right now

**Comment by ghost** [comment]
> It was fixed on last commit

I still get exactly the same error right now.

Following steps from here:

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

https://popcorntime.app suggests latest version is 4.0
but 

```
$ brew cask _stanza version https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb
==> Downloading https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb.
0.4.0
```

**Comment by jacopodisi** [comment]
Is it possible to install `pkg` with `Cask`? Does homebrew allow to install untrusted applications?

**Comment by danielbayley** [comment]
> Is it possible to install `pkg` with `Cask`? Does homebrew allow to install untrusted applications?

@jacopodisi It is… See my PR (#1215): https://github.com/popcorn-official/popcorn-desktop/blob/cbe1424ed088b7e784709deb1acb0b1a7b378a4d/casks/popcorn-time.rb#L13

This issues should be fixed now…

**Comment by rreckonerr** [comment]
@danielbayley same error for stable release
```sh
Error: Checksum for Cask 'popcorn-time' does not match.
Expected: 02bcf7fe9f5a9bc38bd01c7d9107fb138bf49857c182691cd9439fa7a4e9859b
  Actual: 045dbe37d06e24ed7129dddd922648caaba712dee24685fb3cb1f4782f03ead5
    File: /Library/Caches/Homebrew/downloads/03d048fb58f9313525052e93bc9ac1e66c54dd7bdcf21bed0e4c568cbb331c48--Popcorn-Time-0.4.4.pkg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Comment by danielbayley** [comment]
@rreckonerr Should be fixed once #1359 is merged…
