### ISSUE TITLE
Can't filter favorites to only TV

### ISSUE THREAD

**Issue by dammitgabe** [popcorntime/popcorntime#1502]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4-0 "Love in the Time of Corona" Beta

Download date:
~April 30 2020

#### Expected Behaviour
There is a filter option in the favorites tab called "type" with the options of All, Movies, TV and Anime. The expected behavior is that selecting TV would show only the TV shows I have favorited. 

#### Actual Behaviour
When I sort by "All" or "Movies", it works as expected. "All" shows both movies and tv, and "Movies" shows just movies. But when I sort by TV it is blank even though I do have TV series in my favorites, which is confirmed by the fact that they are filtered out when selecting the Movie type. (I do not have any anime so I cannot confirm whether that option works. I do know that my TV series are not being missorted as anime because that option also results in an empty list)

#### Steps to reproduce the behaviour
1. Have at least some TV series tagged as a favorite, as well as movies
2. Open the favorites tab, and confirm that both movies and tv shows are being displayed in the default view
3. Click "Type" and select "TV". The result will be a blank screen that says "No Favorites found..."

#### Screenshot of error from developer console (optional)
Image 1 shows the default view of my Favorites tab. As you can see I have both movies and tv shows favorited (such as Hotel Hell and Swamp Thing)
![image](https://user-images.githubusercontent.com/44794590/83375080-be870700-a39b-11ea-8bcd-937112b62df5.png)

Image 2 shows what happens when I filter by only TV. The result is empty
![image](https://user-images.githubusercontent.com/44794590/83375091-c5ae1500-a39b-11ea-93cb-894c24b0ca03.png)

**Comment by dutchy1001** [comment]
I can confirm this with the latest dev build 424. 
Movies get sorted out but tv shows will give an empty page.

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by dammitgabe** [comment]
Why did you mark this as fixed? I'm on version 4.4 and it is still an issue

**Comment by dammitgabe** [comment]
> @Persei08 issue is fixed, close please

Why did you mark this as fixed? I'm on version 4.4 and it is still an issue

**Comment by dutchy1001** [comment]
Did you update to latest dev build [437](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/437/)? 
That version has it fixed for me.

**Comment by kiriles90** [comment]
@dammitgabe what @dutchy1001 said, its not fixed in 0.4.4 (build 413) but its fixed in the latest dev build (build 437 at the moment)

**Comment by dammitgabe** [comment]
oh ok, my bad. I'm new to this I'll have to figure out how to get the dev build, thanks

**Comment by dutchy1001** [comment]
get the dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by dammitgabe** [comment]
awesome, everything works, thanks!
