### ISSUE TITLE
Subtitle and movie cover issue when using download button

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#1686]
Operating System Version:
Windows 10

Download date:
In the last week (Build 437)

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/437/

#### Expected Behaviour
When using the download button the subtitles and movie covers should download aswell
...

#### Actual Behaviour
It download the movie but not the subtitles or cover
...

#### Steps to reproduce the behaviour

1. Set a default subtitle in the settings ( I tried Dutch and English)
2. Choose a movie to download.
3. Check download folder, Movie and a JPEG but no subtitle or cover file. (It does somtimes add an "empty"  .srt file, see attachment)

#### Screenshot of error from developer console (F12 key (win & linux) or ⌘+⌥+i (macOS), then 'console' tab) (optional)
[Guns.Akimbo.2019.1080p.WEBRip.x264.AAC5.1-[YTS.MX].srt.txt](https://github.com/popcorn-official/popcorn-desktop/files/5233425/Guns.Akimbo.2019.1080p.WEBRip.x264.AAC5.1-.YTS.MX.srt.txt)

[Console output.txt](https://github.com/popcorn-official/popcorn-desktop/files/5233437/Console.output.txt)
Dont think there is an error about the subs here.

**Comment by kiriles90** [comment]
@dutchy1001 do you know if they were downloaded in any previous builds or not downloading the subtitles was always the case with the seedbox?

**Comment by dutchy1001** [comment]
it was in previous builds but forgot about it till few days ago as I was asked to get a movie for a family member. Not sure how far back this was.
If time lets me I will try and find out when the issue started.

**Comment by kiriles90** [comment]
Yeah, seem this was never added, will try and see if its easy to implement without making a mess when I get some time.

**Comment by dutchy1001** [comment]
great, saves me then install/uninstall multiple versions to find the first build it happened with.

**Comment by kiriles90** [comment]
@dutchy1001 do you have a reddit acc or something else I could send a pm to?  
(p.s deleting this message, you'll see the notification, no need for anyone else to see it:)

**Comment by dutchy1001** [comment]
I don't have a reddit account, but I have many others, google search dutchy1001 and an avatar of uncle fester will bring up plenty.
You might like to join here https://discuss.popcorntime.app/, I'm there too 😉😉

(Deleting this too)

**Comment by dutchy1001** [comment]
Any more progress on this bug?
Just downloaded 2 episodes to watch later but it still skipped the subs download.

**Comment by kiriles90** [comment]
No idea if anyone else looked at it but I didnt. There is #1452 that adds it but it also adds a lot of other stuff that either have been fixed, changed and/or have conflicts and cant be merged. The OP never responded to my message either so I guess someone else will either have to separate the subtitles feature or rewrite it. Not forgetting it though, I'm also interested in fixing this.

**Comment by kiriles90** [comment]
Editing the title to include movie covers since now after #1920 they are also being saved when using the 'Watch now' button and its pretty much the same thing thats required for them to also be saved with the 'Download' button as the subtitles.

**Comment by dutchy1001** [comment]
This is still happening, download a series episode but no subs

**Comment by kiriles90** [comment]
@dutchy1001 Who said it was fixed? :)

(if it was #1920 above that created the confusion, its linked for a different reason, its in its description. This issue is still open though none closed it)
