### ISSUE TITLE
Watch button wont work

### ISSUE THREAD

**Issue by Movielover23** [popcorntime/popcorntime#2010]
when i click the watch now button nothing happens, i keep clicking it over and over but nothing happens. I've quit the browser and restarted my laptop but it still wont work.

**Comment by Movielover23** [comment]
Actually I've found that i simply can't watch a series but i can watch a movie, does anyone know how to fix this?

**Comment by kiriles90** [comment]
Update to the latest build from ci.popcorntime.app then make sure whatever you are trying to watch has some seeds.

Closing this since this issue has been fixed for almost a year now.

**Comment by MathD23** [comment]
hello i have dowloaded the latest popcorn time -0.4.4-win64  and the watch now button is still not responding for the series.

**Comment by kiriles90** [comment]
@MathD23 you downloaded the latest release version not the latest build (0.4.4 = build 413)  
Visit ci.popcorntime.app and download the latest build (452 at the moment)

**Comment by dutchy1001** [comment]
I think I might be wise to update the "official" version on the website to a "newer" dev build. It would solve a lot of issue's ppl have with that version (Build 413) that is available on there.
If they have a newer (dev) build to download from the official site you get more up to date issue's reported and less issue's that are already fixed.

**Comment by MathD23** [comment]
@kiriles90 between all does build found on 452 bellow what is the latest build:

Artefacts du build
Popcorn-Time-0.4.4-win32-Setup.exe88.83 
Popcorn-Time-0.4.4-win64-Setup.exe
Popcorn-Time-0.4.4_linux32.zip
Popcorn-Time-0.4.4_linux64.zip
Popcorn-Time-0.4.4_osx64.zip
Popcorn-Time-0.4.4_win32.zip
Popcorn-Time-0.4.4_win64.zip
popcorn-time_0.4.4-amd64.deb97.08 MB viewpopcorn-time_0.4.4-i386.deb99.45 MB viewupdate-0.4.4_linux32.zip149.15 MB viewupdate-0.4.4_linux64.zip144.74 MB viewupdate-0.4.4_osx64.zip144.14 MB view |   | Popcorn-Time-0.4.4-win32-Setup.exe | 88.83 MB | view |   | Popcorn-Time-0.4.4-win64-Setup.exe | 90.15 MB | view |   | Popcorn-Time-0.4.4_linux32.zip | 155.83 MB | view |   | Popcorn-Time-0.4.4_linux64.zip | 151.41 MB | view |   | Popcorn-Time-0.4.4_osx64.zip | 221.02 MB | view |   | Popcorn-Time-0.4.4_win32.zip | 138.97 MB | view |   | Popcorn-Time-0.4.4_win64.zip | 142.22 MB | view |   | popcorn-time_0.4.4-amd64.deb | 97.08 MB | view |   | popcorn-time_0.4.4-i386.deb | 99.45 MB | view |   | update-0.4.4_linux32.zip | 149.15 MB | view |   | update-0.4.4_linux64.zip | 144.74 MB | view |   | update-0.4.4_osx64.zip | 144.14 MB | view
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Popcorn-Time-0.4.4-win32-Setup.exe | 88.83 MB | view
  | Popcorn-Time-0.4.4-win64-Setup.exe | 90.15 MB | view
  | Popcorn-Time-0.4.4_linux32.zip | 155.83 MB | view
  | Popcorn-Time-0.4.4_linux64.zip | 151.41 MB | view
  | Popcorn-Time-0.4.4_osx64.zip | 221.02 MB | view
  | Popcorn-Time-0.4.4_win32.zip | 138.97 MB | view
  | Popcorn-Time-0.4.4_win64.zip | 142.22 MB | view
  | popcorn-time_0.4.4-amd64.deb | 97.08 MB | view
  | popcorn-time_0.4.4-i386.deb | 99.45 MB | view
  | update-0.4.4_linux32.zip | 149.15 MB | view
  | update-0.4.4_linux64.zip | 144.74 MB | view
  | update-0.4.4_osx64.zip | 144.14 MB | view

**Comment by dutchy1001** [comment]
This is the link direct to the latest build:
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/
Pick the one for your OS either a x86 or x64 bit build

**Comment by MathD23** [comment]
@dutchy1001 thank you i will try the x64 and i will keep you update

**Comment by MathD23** [comment]
i download the popcorn version 6.2 and i can watch and dowload my movies and series

**Comment by dutchy1001** [comment]
version 6.2?? I don't think we got that version, you sure you got the right PCT? Think that version number is from a different fork.

**Comment by kiriles90** [comment]
Version 6.2 is Time4Popcorn not Popcorn Time. Different app.

**Comment by MathD23** [comment]
yh its from a different fork
