### ISSUE TITLE
Stuck loading show from Watchlist

### ISSUE THREAD

**Issue by ZedoGado** [popcorntime/popcorntime#273]
Operating System Version:
Windows 10 x64

Popcorn Time Version:
Build #169

Download date:
27 October 2016
#### Expected Behaviour

Open selected show from Watchlist and display show details
#### Actual Behaviour

Spinner stays visible with no page load.
#### Steps to reproduce the behaviour
1. Click Watchlist
2. Select any show synced from Traktv

I have tried the last two builds and still the same behaviour .

Console log:
[INFO] Returning cached provider Watchlist
item.js:255 Uncaught TypeError: provider.detail(...).then is not a function(…)
app.js:21 [ERROR] TypeError: provider.detail(...).then is not a function TypeError: provider.detail(...).then is not a function
    at n.showDetail (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/views/browser/item.js:255:22)
    at HTMLLIElement.dispatch (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/jquery/dist/jquery.min.js:3:10315)
    at HTMLLIElement.q.handle (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/jquery/dist/jquery.min.js:3:8342)

**Comment by team-pct** [comment]
Duplicate  #121

**Comment by maclir** [comment]
I have the same issue from the mac build here: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/175/

@team-pct This is not a duplicate of #121. That is about opening the watchlist. In this case watchlist loads properly, but when you select a show from the list it does not load it.

```
item.js:255 Uncaught TypeError: provider.detail(...).then is not a function(…)showDetail @ item.js:255dispatch @ jquery.min.js:3q.handle @ jquery.min.js:3

app.js:21 [ERROR] TypeError: provider.detail(...).then is not a function TypeError: provider.detail(...).then is not a function
    at n.showDetail (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/views/browser/item.js:255:22)
    at HTMLLIElement.dispatch (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/jquery/dist/jquery.min.js:3:10315)
    at HTMLLIElement.q.handle (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/jquery/dist/jquery.min.js:3:8342)win.error @ app.js:21(anonymous function) @ app.js:699emitOne @ events.js:96emit @ events.js:188process._fatalException @ bootstrap_node.js:313
```

**Comment by JimiC** [comment]
After facing the same issue (on Windows) I looked into it and found the following.

**Problem:**
The error appears in `item.js` line 254.
Movies and Series providers  (MovieAPI and TVApi respectfully) have a `detail` function which is promisable and therefore can handle the `then/catch` chained functions, but `watchlist` provider function isn't (the function signature actually expects a callback function), resulting to the error.

**Solution:**
Proposed solution would be to make the `detail` function, of the `watchlist` provider, a promisable function too.

**Comment by maclir** [comment]
@JimiC I was looking into making a pull request to fix this, but I could not find a `detail` function in the `watchlist` provider. Have you been able to fix this?

**Comment by JimiC** [comment]
@maclir https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/watchlist.js#L200

**Comment by maclir** [comment]
@JimiC Looks like it has been fixed in the butter project. https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/providers/watchlist.js#L185-L206 Perhaps a simple merge would fix this?

**Comment by JimiC** [comment]
@maclir Worth a try.

**Comment by Midifreakz** [comment]
This issue is still taking place over one year later... Has this solution ever been implemented?
